
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jvaxvvdwxmjzufqsqrud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2YXh2dmR3eG1qenVmcXNxcnVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDMxNzcsImV4cCI6MjA2NDAxOTE3N30.MK1WY1Bvum0aab3Ul_aWOHUTbvxgEx2g0f7-Ao9nrrY";

// Database schema type
export interface Database {
  public: {
    Tables: {
      ingredients: {
        Row: {
          id: string;
          name: string;
          unit: string;
          cost_per_unit: number;
          supplier: string | null;
          current_stock: number | null;
          min_stock_threshold: number | null;
          category: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          unit?: string;
          cost_per_unit: number;
          supplier?: string | null;
          current_stock?: number | null;
          min_stock_threshold?: number | null;
          category?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          unit?: string;
          cost_per_unit?: number;
          supplier?: string | null;
          current_stock?: number | null;
          min_stock_threshold?: number | null;
          category?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      recipes: {
        Row: {
          id: string;
          name: string;
          category: string;
          preparation_time: number;
          difficulty: string;
          portions: number;
          description: string | null;
          allergens: string | null;
          calories: number | null;
          protein: number | null;
          carbs: number | null;
          fat: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          category: string;
          preparation_time: number;
          difficulty: string;
          portions: number;
          description?: string | null;
          allergens?: string | null;
          calories?: number | null;
          protein?: number | null;
          carbs?: number | null;
          fat?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          category?: string;
          preparation_time?: number;
          difficulty?: string;
          portions?: number;
          description?: string | null;
          allergens?: string | null;
          calories?: number | null;
          protein?: number | null;
          carbs?: number | null;
          fat?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      recipe_ingredients: {
        Row: {
          id: string;
          recipe_id: string | null;
          ingredient_id: string | null;
          quantity: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id?: string | null;
          ingredient_id?: string | null;
          quantity: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string | null;
          ingredient_id?: string | null;
          quantity?: number;
          created_at?: string;
        };
      };
      recipe_instructions: {
        Row: {
          id: string;
          recipe_id: string | null;
          step_number: number;
          instruction: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id?: string | null;
          step_number: number;
          instruction: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string | null;
          step_number?: number;
          instruction?: string;
          created_at?: string;
        };
      };
      dishes: {
        Row: {
          id: string;
          name: string;
          category: string;
          selling_price: number;
          recipe_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          category: string;
          selling_price: number;
          recipe_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          category?: string;
          selling_price?: number;
          recipe_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
