// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jvaxvvdwxmjzufqsqrud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2YXh2dmR3eG1qenVmcXNxcnVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDMxNzcsImV4cCI6MjA2NDAxOTE3N30.MK1WY1Bvum0aab3Ul_aWOHUTbvxgEx2g0f7-Ao9nrrY";

// Database schema type
export interface Database {
  public: {
    Tables: {
      ingredients: {
        Row: {
          id: string;
          name: string;
          unit: string;
          cost_per_unit: number;
          supplier: string | null;
          current_stock: number | null;
          allocated_stock: number;
          min_stock_threshold: number | null;
          category: string | null;
          restaurant_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          unit?: string;
          cost_per_unit: number;
          supplier?: string | null;
          current_stock?: number | null;
          allocated_stock?: number;
          min_stock_threshold?: number | null;
          category?: string | null;
          restaurant_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          unit?: string;
          cost_per_unit?: number;
          supplier?: string | null;
          current_stock?: number | null;
          allocated_stock?: number;
          min_stock_threshold?: number | null;
          category?: string | null;
          restaurant_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      storage_locations: {
        Row: {
          id: string;
          restaurant_id: string;
          name: string;
          type: string;
          temperature_min: number | null;
          temperature_max: number | null;
          capacity_description: string | null;
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          name: string;
          type?: string;
          temperature_min?: number | null;
          temperature_max?: number | null;
          capacity_description?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          name?: string;
          type?: string;
          temperature_min?: number | null;
          temperature_max?: number | null;
          capacity_description?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      inventory_movements: {
        Row: {
          id: string;
          restaurant_id: string;
          ingredient_id: string;
          label_id: string | null;
          movement_type: string;
          quantity_change: number;
          quantity_before: number;
          quantity_after: number;
          allocated_quantity_change: number | null;
          notes: string | null;
          created_by_user_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          ingredient_id: string;
          label_id?: string | null;
          movement_type: string;
          quantity_change: number;
          quantity_before: number;
          quantity_after: number;
          allocated_quantity_change?: number | null;
          notes?: string | null;
          created_by_user_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          ingredient_id?: string;
          label_id?: string | null;
          movement_type?: string;
          quantity_change?: number;
          quantity_before?: number;
          quantity_after?: number;
          allocated_quantity_change?: number | null;
          notes?: string | null;
          created_by_user_id?: string | null;
          created_at?: string;
        };
      };
      ingredient_allocations: {
        Row: {
          id: string;
          restaurant_id: string;
          ingredient_id: string;
          label_id: string;
          allocated_quantity: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          ingredient_id: string;
          label_id: string;
          allocated_quantity?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          ingredient_id?: string;
          label_id?: string;
          allocated_quantity?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      labels: {
        Row: {
          id: string;
          label_type: string;
          title: string;
          batch_number: string | null;
          production_date: string | null;
          expiry_date: string | null;
          quantity: number | null;
          unit: string | null;
          storage_instructions: string | null;
          allergens: string | null;
          supplier: string | null;
          notes: string | null;
          status: string | null;
          recipe_id: string | null;
          ingredient_id: string | null;
          dish_id: string | null;
          storage_location_id: string | null;
          ingredient_traceability: any[];
          restaurant_id: string;
          qr_data: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          label_type: string;
          title: string;
          batch_number?: string | null;
          production_date?: string | null;
          expiry_date?: string | null;
          quantity?: number | null;
          unit?: string | null;
          storage_instructions?: string | null;
          allergens?: string | null;
          supplier?: string | null;
          notes?: string | null;
          status?: string | null;
          recipe_id?: string | null;
          ingredient_id?: string | null;
          dish_id?: string | null;
          storage_location_id?: string | null;
          ingredient_traceability?: any[];
          restaurant_id: string;
          qr_data: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          label_type?: string;
          title?: string;
          batch_number?: string | null;
          production_date?: string | null;
          expiry_date?: string | null;
          quantity?: number | null;
          unit?: string | null;
          storage_instructions?: string | null;
          allergens?: string | null;
          supplier?: string | null;
          notes?: string | null;
          status?: string | null;
          recipe_id?: string | null;
          ingredient_id?: string | null;
          dish_id?: string | null;
          storage_location_id?: string | null;
          ingredient_traceability?: any[];
          restaurant_id?: string;
          qr_data?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      recipes: {
        Row: {
          id: string;
          name: string;
          category: string;
          preparation_time: number;
          difficulty: string;
          portions: number;
          description: string | null;
          allergens: string | null;
          calories: number | null;
          protein: number | null;
          carbs: number | null;
          fat: number | null;
          is_semilavorato: boolean | null;
          notes_chef: string | null;
          selling_price: number | null;
          restaurant_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          category: string;
          preparation_time: number;
          difficulty: string;
          portions: number;
          description?: string | null;
          allergens?: string | null;
          calories?: number | null;
          protein?: number | null;
          carbs?: number | null;
          fat?: number | null;
          is_semilavorato?: boolean | null;
          notes_chef?: string | null;
          selling_price?: number | null;
          restaurant_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          category?: string;
          preparation_time?: number;
          difficulty?: string;
          portions?: number;
          description?: string | null;
          allergens?: string | null;
          calories?: number | null;
          protein?: number | null;
          carbs?: number | null;
          fat?: number | null;
          is_semilavorato?: boolean | null;
          notes_chef?: string | null;
          selling_price?: number | null;
          restaurant_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      recipe_ingredients: {
        Row: {
          id: string;
          recipe_id: string | null;
          ingredient_id: string | null;
          quantity: number;
          is_semilavorato: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id?: string | null;
          ingredient_id?: string | null;
          quantity: number;
          is_semilavorato?: boolean | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string | null;
          ingredient_id?: string | null;
          quantity?: number;
          is_semilavorato?: boolean | null;
          created_at?: string;
        };
      };
      recipe_instructions: {
        Row: {
          id: string;
          recipe_id: string | null;
          step_number: number;
          instruction: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id?: string | null;
          step_number: number;
          instruction: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string | null;
          step_number?: number;
          instruction?: string;
          created_at?: string;
        };
      };
      dishes: {
        Row: {
          id: string;
          name: string;
          category: string;
          selling_price: number;
          recipe_id: string | null;
          restaurant_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          category: string;
          selling_price: number;
          recipe_id?: string | null;
          restaurant_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          category?: string;
          selling_price?: number;
          recipe_id?: string | null;
          restaurant_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      restaurants: {
        Row: {
          id: string;
          name: string;
          type: string;
          country: string;
          city: string;
          vat_number: string | null;
          seats_count: number | null;
          owner_user_id: string | null;
          subscription_status: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type?: string;
          country: string;
          city: string;
          vat_number?: string | null;
          seats_count?: number | null;
          owner_user_id?: string | null;
          subscription_status?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: string;
          country?: string;
          city?: string;
          vat_number?: string | null;
          seats_count?: number | null;
          owner_user_id?: string | null;
          subscription_status?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role: string;
          restaurant_id: string;
          password_hash: string;
          email_verified_at: string | null;
          last_login_at: string | null;
          reset_password_token: string | null;
          reset_password_expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          full_name: string;
          role?: string;
          restaurant_id: string;
          password_hash: string;
          email_verified_at?: string | null;
          last_login_at?: string | null;
          reset_password_token?: string | null;
          reset_password_expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role?: string;
          restaurant_id?: string;
          password_hash?: string;
          email_verified_at?: string | null;
          last_login_at?: string | null;
          reset_password_token?: string | null;
          reset_password_expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
